### ISSUE TITLE
Misc issues related to the model update

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-common#47]
(To be completed)

* [x] When I create a new package in IntelliJ, I can't import it from other packages of the same module (it looks like the package is not added to the model)
* [x] When I create a new module in IntelliJ, I can't import it from other modules of the same IntelliJ module
* [x] When I call the quick fix that automatically adds a module import in IntelliJ, `module.ceylon` is modified but the current file still shows an error on the import statement
* [x] When I call the quick fix that automatically makes a declaration `shared` in another file, that other file is modified but the global model is not updated, i.e. I have to make a fake edit to that other file to see the change in the current file

**Comment by davidfestal** [comment]
The various cases now are working correctly, apart from the fact that all these changes takes 4 seconds to be visible (the automatic model update timeout).
Since these are explicit manual actions, I'll reduce this timeout to 0 in this case, so that the model update and subsequent local typechecking of opened editors will be scheduled immediately and systematically after these actions.

**Comment by davidfestal** [comment]
@bjansen : This is completely fixed now in all the tests I did. do you confirm that I can close it ?

**Comment by bjansen** [comment]
Yes, it seems everything is now fixed, thanks!
